### ISSUE TITLE
Wrong version number display in the core app after upgrade

### ISSUE THREAD

**Issue by pp-r** [YunoHost-Apps/zwiicms_ynh#15]
### Describe the bug

*I noticed that the version number after the upgrade was not propagated in the core application files or the new files do not overwrite the previous ones.*

### Context

- Hardware: *Other ARM board*
- YunoHost version: 11.1.17
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: exotic ssh port

### Steps to reproduce

- *Upgrade from 12.3.04 to 12.3.05 ... but i noticed that this was already the case for the previous versions and this update confirms it.*

### Expected behavior

*Once login in the application, it should not ask to be updated and the correct version number should be updated in several files.*

### Logs

cd /var/www/zwiicms
cat /var/www/zwiicms/ | grep -r 12.3.04 *
CHANGES.md:## Version 12.3.04
cat: /var/www/zwiicms/: Is a directory
core/core.php:	const ZWII_VERSION = '12.3.04';
LISEZMOI.md:# ZwiiCMS 12.3.04
README.md:# ZwiiCMS 12.3.04

In core/core.php:
[...]
// Numéro de version et branche pour l'auto-update
        const ZWII_VERSION = '12.3.04';
[...]

That instead of 12.3.05. Maybe some files don't overwrite old one during the upgrade or something else.
Once login in the admin panel of the app, if i do or force the update of the app by his own process, all seems to be right after that : the README.md, LISEZMOI.md, CHANGE.md and the core/core.php files are well up-to-date with the right version number and the full changelog for example including the new version 12.3.05 which is previously don't include it and show only the 12.3.04 and before.

**Comment by ewilly** [comment]
Should be partially solved by upgrading the app with that command `yunohost app upgrade zwiicms -u https://github.com/YunoHost-Apps/zwiicms_ynh/tree/testing --debug --force`

I say partially because by using the own update proccess of the app it apply some changes that are not applied with the current ynh upgrade process.
Those changes are manage by `/var/www/zwiicms/core/include/update.inc.php` and are varioulsy applied: 
* removing old files  (files preserved in the ynh upgrade proccess).
* updating files in `/var/www/zwiicms/site`  (files preserved in the ynh upgrade proccess).
We have to figure out how to handle such process...
